tupla = (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
print(tupla[1])
print(tupla[-2])
print(tupla[2:7])
print(tupla[::3])
print(tupla[::-2])
print(tupla[-2::-2])
print(len(tupla))

lista = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(lista[0])
# print(dir(lista))

print(lista)
lista.append("AA")
print(lista)
print(id(lista))
lista.extend(['a','b'])
print(lista)
lista.append(['a', 'b'])
print(lista)
print(lista[-1][-1])
print(" Jak działa pop")
print(lista)
print(lista.pop())
print(lista)
print("Sortowanie")
print(lista.sort())
